---

- hosts: jenkins
  become: true
  gather_facts: yes
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: geerlingguy.docker
    - role: chouseknecht.gcloud
  tasks:
    - name: Install additional packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
