---

- name: geerlingguy.jenkins
  scm: git
  src: git@github.com:geerlingguy/ansible-role-jenkins.git
  version: 3.7.0

- name: geerlingguy.java
  scm: git
  src: git@github.com:geerlingguy/ansible-role-java.git
  version: 1.9.5

- name: geerlingguy.docker
  scm: git
  src: git@github.com:geerlingguy/ansible-role-docker.git
  version: 2.5.2

- name: andrzej-tests-1.sshguard
  scm: git
  src: git@github.com:andrzej-tests-1/ansible-role-sshguard.git
  version: 1.0.0

- name: gantsign.helm
  scm: git
  src: git@github.com:gantsign/ansible_role_helm.git
  version: 1.5.0

